# Generated by Django 3.1.4 on 2020-12-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpost',
            old_name='discription',
            new_name='discraption',
        ),
    ]
