# Generated by Django 3.1.4 on 2020-12-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201215_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpost',
            old_name='discraption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='adminpost',
            name='thumbnail',
            field=models.ImageField(upload_to='imagess'),
        ),
    ]
