# Generated by Django 3.1.4 on 2021-01-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201221_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.BooleanField(max_length=1)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='adminpost',
            name='category',
            field=models.ManyToManyField(to='post.Category'),
        ),
    ]
