# Generated by Django 3.1.4 on 2021-04-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210407_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpost',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
