# Generated by Django 3.1.4 on 2021-04-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
