# Generated by Django 3.1.4 on 2021-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='adminpost',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='post.IPAddress'),
        ),
    ]
