# Generated by Django 3.1.4 on 2021-04-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210425_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpost',
            name='hits',
        ),
    ]
