# Generated by Django 3.1.4 on 2021-04-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_adminpost_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.adminpost')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='adminpost',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='post.ArticleHit', to='post.IPAddress'),
        ),
    ]
