# Generated by Django 3.1.4 on 2021-04-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20210428_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
