# Generated by Django 3.1.4 on 2021-04-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
